# list/Makefile
#
# Makefile for list implementation and test file.
#
# <Sara Braddock>

main: main.c
  gcc main.c -o mainfile

listC: list.c
  gcc list.c -o listC

listH: list.h
  gcc list.h -o listH
